-- Legado: use scripts/sql/dados_cliente_inscricao_form_status.sql (inclui reativacao_* + inscricao_form_status).
-- Sumaré produção: tabela dados_cliente_sum — rode dados_cliente_inscricao_form_status.sql no SQL Editor.
