-- Catálogo de códigos de curso — API Captação Sumaré (planilha codigos polos.xlsx)
-- Usado pelo agente para mapear sum_Curso / nome informado → parâmetro curso na inscrição.

CREATE TABLE IF NOT EXISTS public.sumare_captacao_curso (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_original text NOT NULL,
  codigo_base text NOT NULL,
  curso_nome text NOT NULL,
  modalidade text NOT NULL DEFAULT 'Não informado',
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT sumare_captacao_curso_codigo_original_key UNIQUE (codigo_original)
);

CREATE INDEX IF NOT EXISTS sumare_captacao_curso_curso_nome_idx
  ON public.sumare_captacao_curso (lower(curso_nome));

CREATE INDEX IF NOT EXISTS sumare_captacao_curso_codigo_base_idx
  ON public.sumare_captacao_curso (codigo_base);

CREATE INDEX IF NOT EXISTS sumare_captacao_curso_modalidade_idx
  ON public.sumare_captacao_curso (modalidade);

COMMENT ON TABLE public.sumare_captacao_curso IS
  'Códigos de curso para GET /api-ingresso/candidato/gerar (API Captação Sumaré).';

COMMENT ON COLUMN public.sumare_captacao_curso.codigo_original IS
  'Código enviado na query curso= (ex. HIST_EAD, ADM_4_EAD).';

COMMENT ON COLUMN public.sumare_captacao_curso.codigo_base IS
  'Prefixo do curso sem sufixo de modalidade (ex. HIST, ADM).';

COMMENT ON COLUMN public.sumare_captacao_curso.modalidade IS
  'EAD | Semipresencial | Não informado';
